### ISSUE TITLE
What is HasMalformedDirectives?

### ISSUE THREAD

**Issue by bakkot** [binast/ecmascript-binary-ast#44]
I don't understand what this assertion is meant to accomplish. Naively it looks like it would forbid
```js
"directive";
("directive");
```

which I don't think it should?

**Comment by syg** [comment]
Nice catch. I definitely didn't intend to forbid that case.

The intention was to forbid a set of textually inexpressible programs to be expressible in binary AST through round tripping. Since binary AST is run through Ecmaify to have any meaning at all, it'd be bad if a binary AST like

```
Directives = []
Statements = ["use strict"]
```

ended up meaning the same thing as 

```
Directives = ["use strict"]
Statements = []
```

Since an actual binary AST implementation would not interpret the first program as being in strict mode.

I haven't looked at HasMalformedDirectives since the very first drafts of the spec, and it looks like it's just really wrong.

Your example gives a really nice and simple fix: Ecmaify could parenthesize all top-level statements of string literals.

What do you think?

**Comment by bakkot** [comment]
> Your example gives a really nice and simple fix: Ecmaify could parenthesize all top-level statements of string literals.

Sounds good to me. That's what code generators like [prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdEATAlgJzmGLANznQG5UoBnGAQ3gFsEYKp0acsoBzckAGhAQADoWhVkoWjhwQA7gAVpCCSlpEIWDAJAAjHLTABrODADKww127IYOAK5xBXKnBwwFB7g1rIAZrQANq6CAFZUAB4AQgbGpma0TAAyXHD+QSEgljiuOMh6tLoAnoHQOsKcsADqWjAAFsgAHAAMghUQrlUGwvkVcLkkOngAjva4cJ603r5IAcFOIK4MWLYOC1TWgXAAivYQ8OnzgnS6NRj1yABMxwZYgdYAwhAMPvlQ0GmC9q4AKoWqc1cAF8gUA) do, for example.

You can be aggressive about it and only do so for the very first statement in a function body or script, which is what code generators which are trying to produce the smallest possible code for a given AST [do](https://github.com/shapesecurity/shift-codegen-js/blob/es2016/src/minimal-codegen.js#L392), but I don't think there's a need.

**Comment by syg** [comment]
> Edit: In fact if you want to do the simplest thing you can just parenthesize all string literals everywhere. Doesn't hurt anything, I think, unless F.p.toString is specified in terms of the AST resulting from Ecmaify.

Yeah, I considered that, since it doesn't hurt anything like you said. Decided against it since it muddles intentions a little bit.
